# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mikeo7-github'
    scannerMode: 'Other'

- script: |
    echo Starting the build
    mvn sonar:sonar \
      -Dsonar.projectKey=MikeO7_pipelines-java \
      -Dsonar.organization=mikeo7-github \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.login=b22a40c973ba53e682f4b253a2c1b5fe30688931
  displayName: 'Build with Maven'

- task: SonarCloudAnalyze@1